// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCbOIz3L04t9h9JaJvxUsGzImoPYRF9fw',
    appId: '1:653630050865:web:92904a852a2d47d8903b10',
    messagingSenderId: '653630050865',
    projectId: 'shortvideo-30409',
    authDomain: 'shortvideo-30409.firebaseapp.com',
    databaseURL: 'https://shortvideo-30409-default-rtdb.firebaseio.com',
    storageBucket: 'shortvideo-30409.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0tgafd0E_esTf_Gr7K6INq5oSMhNB3fI',
    appId: '1:653630050865:android:b5f758c38313212e903b10',
    messagingSenderId: '653630050865',
    projectId: 'shortvideo-30409',
    databaseURL: 'https://shortvideo-30409-default-rtdb.firebaseio.com',
    storageBucket: 'shortvideo-30409.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD94A1kyGcf5aMi62OnoGgaUg0gTuYN9fg',
    appId: '1:653630050865:ios:3b269324796f94f3903b10',
    messagingSenderId: '653630050865',
    projectId: 'shortvideo-30409',
    databaseURL: 'https://shortvideo-30409-default-rtdb.firebaseio.com',
    storageBucket: 'shortvideo-30409.appspot.com',
    iosBundleId: 'com.example.shortvideo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD94A1kyGcf5aMi62OnoGgaUg0gTuYN9fg',
    appId: '1:653630050865:ios:3b269324796f94f3903b10',
    messagingSenderId: '653630050865',
    projectId: 'shortvideo-30409',
    databaseURL: 'https://shortvideo-30409-default-rtdb.firebaseio.com',
    storageBucket: 'shortvideo-30409.appspot.com',
    iosBundleId: 'com.example.shortvideo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCbOIz3L04t9h9JaJvxUsGzImoPYRF9fw',
    appId: '1:653630050865:web:d1fa89e13abab36a903b10',
    messagingSenderId: '653630050865',
    projectId: 'shortvideo-30409',
    authDomain: 'shortvideo-30409.firebaseapp.com',
    databaseURL: 'https://shortvideo-30409-default-rtdb.firebaseio.com',
    storageBucket: 'shortvideo-30409.appspot.com',
  );
}
